version: '3.8'

services:
  web_test:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db_test
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin@db_test:5432/test_new
    volumes:
      - .:/app

  db_test:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: test_new
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



